feat: implement options loading

diff --git a/providers/gcloud/provider.yaml b/providers/gcloud/provider.yaml
--- a/providers/gcloud/provider.yaml
+++ b/providers/gcloud/provider.yaml
@@ -6,14 +6,15 @@ options:
   GCLOUD_BINARY:
     description: Path to the gcloud binary
     default: gcloud
+    before: init
   PROJECT:
-    description: The project to use. If unspecified, will try to retrieve it from the gcloud cli.
-    defaultCommand: |-
-      gcloud ...
+    description: The project id to use.
+    required: true
+    command: ${GCLOUD_BINARY} config list --quiet --verbosity=error --format "value(core.project)"
   ZONE:
-    description: The google cloud zone to create the VM in.
-    defaultCommand: |-
-      gcloud ...
+    description: The google cloud zone to create the VM in. E.g. europe-west1-d
+    required: true
+    command: ${GCLOUD_BINARY} config list --quiet --verbosity=error --format "value(compute.zone)"
   DISK_SIZE:
     description: The disk size to use.
     default: "30"
@@ -23,37 +24,26 @@ options:
   MACHINE_TYPE:
     description: The machine type to use.
     default: e2-standard-2
-  CREATE_ARGS:
-    description: Extra arguments to add during creation
-  ENABLE_SLEEPMODE:
-    description: If inactivity timeout should be enabled.
-    default: "true"
-    enum: ["true", "false"]
-  DELETE_ON_TIMEOUT:
-    description: If the instance should be deleted on inactivity.
-    default: "false"
-    enum: ["true", "false"]
   GCLOUD_TOKEN:
-    dependsOn: ["ENABLE_SLEEPMODE"]
     hidden: true
     cache: 4h
-    command: |-
-      if [ "${ENABLE_SLEEPMODE}" -eq "true" ]; then
-        gcloud auth application-default print-access-token --quiet
-      fi
+    before: command
+    command: ${GCLOUD_BINARY} auth application-default print-access-token --quiet --verbosity=error
 agent:
   path: /run/agent
-  inject: |-
-    ...
-  inactivity:
+  exec:
     shutdown: |-
-      curl ... ${GCLOUD_TOKEN}
+      echo "Shutdown Bro"
 exec:
-  init: ["devpod", "provider", "call", "gcloud", "init"]
-  validate: ...
-  command: ["devpod", "provider", "call", "gcloud", "command"]
-  create: ["devpod", "provider", "call", "gcloud", "create"]
-  delete: ["devpod", "provider", "call", "gcloud", "delete"]
-  start: ["devpod", "provider", "call", "gcloud", "start"]
-  stop: ["devpod", "provider", "call", "gcloud", "stop"]
-  status: ["devpod", "provider", "call", "gcloud", "status"]
+  init: |-
+    if ! command -v ${GCLOUD_BINARY} &> /dev/null; then
+        echo "gcloud command couldn't be found. Please make sure to install the gcloud CLI locally"
+        echo "Take a look at https://cloud.google.com/sdk/docs/install-sdk for more information"
+        exit 1
+    fi
+  command: ${DEVPOD} provider call gcloud command
+  create: ${DEVPOD} provider call gcloud create
+  delete: ${DEVPOD} provider call gcloud delete
+  start: ${DEVPOD} provider call gcloud start
+  stop: ${DEVPOD} provider call gcloud stop
+  status: ${DEVPOD} provider call gcloud status
